FROM python:3.11-slim

RUN apt-get update && apt-get install -y libpq-dev python3-dev

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install -r requirements-bot.txt

CMD ["python3", "telegram_bot.py"]