FROM python:3.11-slim

RUN apt-get update && apt-get install -y libpq-dev python3-dev

WORKDIR /app

COPY . /app

RUN pip install --upgrade pip
RUN pip install -r requirements-streamlit.txt

EXPOSE 8501

CMD ["streamlit", "run", "dashboard.py"]
